jobs:
  refresh-jdk8:
    if: github.repository_owner == 'corretto'
    name: Update Corretto-8
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Fetch Corretto-8 upstream
      uses: ./.github/actions/fetch-repo
      with:
        local-branch: upstream-dev
        upstream: https://github.com/openjdk/jdk8u-dev.git
    - continue-on-error: true
      name: Merge Corretto-8
      uses: ./.github/actions/merge-repo
      with:
        merge-branch: nightly
        upstream: upstream-dev
    - continue-on-error: true
      name: Update Corretto version
      uses: ./.github/actions/update-version
      with:
        upstream: upstream-dev
        version-branch: nightly
name: Refresh from Upstream-dev
on:
  repository_dispatch:
    types: trigger-ga___fetch-dev-repo.yml
